from widgets.backlightwidget import BacklightWidget
from widgets.batterywidget import BatteryWidget
from widgets.capslockwidget import CapslockWidget
from widgets.clockwidget import ClockWidget
from widgets.cpuwidget import CpuWidget
from widgets.memwidget import MemWidget
from widgets.netwidget import NetWidget
from widgets.volumewidget import VolumeWidget
from widgets.winname import WinName
